In [16]:
import pandas as pd
s=pd.DataFrame({"Name":["Maheen","Anvitha","Maheen","Fathima","Fathima"],
                "Age":[20,19,20,21,21]})      #to  find duplicates
print(s.duplicated())

0    False
1    False
2     True
3    False
4     True
dtype: bool

In [17]:
import pandas as pd
s=pd.DataFrame({"Name":["Maheen","Anvitha","Maheen","Fathima","Fathima"],
                "Age":[20,19,20,21,21]})
print(s.drop_duplicates())   #to drop duplicate

      Name  Age
0   Maheen   20
1  Anvitha   19
3  Fathima   21

In [3]:
import pandas as pd
employee={"Name":["Alex","Max","Mira","Ayesha","Pooja"],
          "Salary":[30000,50000,40000,55000,45000]}
eply=pd.DataFrame(employee)
print(eply)

     Name  Salary
0    Alex   30000
1     Max   50000
2    Mira   40000
3  Ayesha   55000
4   Pooja   45000

In [9]:
print(eply[eply["Salary"]>45000])   #manual way

     Name  Salary
1     Max   50000
3  Ayesha   55000

In [11]:
print(eply.query("Salary>45000"))  #query method -use for filtering

     Name  Salary
1     Max   50000
3  Ayesha   55000

In [13]:
print(eply.query("Salary<55000 and Salary>40000"))

    Name  Salary
1    Max   50000
4  Pooja   45000

In [15]:
#random sample
movie={"moviename":["DDLJ","PRDP","Race","DON"]}
name=pd.DataFrame(movie)
print(name)

  moviename
0      DDLJ
1      PRDP
2      Race
3       DON

In [18]:
print(name.sample(2))

  moviename
0      DDLJ
3       DON

In [26]:
name.sample(2,random_state=1)

  moviename
3       DON
2      Race

In [63]:
name.sample(3,random_state=0)

  moviename
2      Race
3       DON
1      PRDP

In [ ]:
#DATETIME

In [60]:
dt={"Date":["2026-12-2","2026-12-6","2026-12-2","2026-12-8","2026-12-7"]}
t=pd.DataFrame(dt)
print(t)

        Date
0  2026-12-2
1  2026-12-6
2  2026-12-2
3  2026-12-8
4  2026-12-7

In [62]:
t["Date"]=pd.to_datetime(t["Date"])
print(t)

        Date
0 2026-12-02
1 2026-12-06
2 2026-12-02
3 2026-12-08
4 2026-12-07

In [48]:
t["Date"].dt.month

0    12
1    12
2    12
3    12
4    12
Name: Date, dtype: int32

In [54]:
t["Date"].dt.year

0    2026
1    2026
2    2026
3    2026
4    2026
Name: Date, dtype: int32

In [53]:
t["Date"].dt.day_name()

0    Wednesday
1       Sunday
2    Wednesday
3      Tuesday
4       Monday
Name: Date, dtype: object

In [52]:
pd.Timestamp.now()

Timestamp('2026-06-18 16:22:39.585416')

In [59]:
from datetime import  datetime
date=datetime(2026,6,12)
date1=datetime(2026,6,17)
print(date1-date)

5 days, 0:00:00

In [4]:
import pandas as pd
s=pd.DataFrame({"range":[1,2,3,4,5,6,7,8,9],
                "ra":[11,12,13,14,15,16,17,18,19]})
print(s.sample(4,random_state=1))

   range  ra
8      9  19
2      3  13
6      7  17
7      8  18

In [5]:
import pandas as pd 
s=pd.DataFrame({"range":[1,2,3,4,5,6,7,8,9],
                "ra":[11,12,13,14,15,16,17,18,19]})
print(s.sample(3,random_state=0))

   range  ra
7      8  18
2      3  13
1      2  12

In [6]:
data=pd.Series(range(1,10))
print(data.sample(5))

2    3
8    9
0    1
1    2
5    6
dtype: int64

In [16]:
data=pd.Series(range(1,10))
print(data.sample(frac=0.2))

2    3
6    7
dtype: int64